"""
Django settings for server project.

Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import pymysql

pymysql.install_as_MySQLdb()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-t#-d*_tp$1xih2+2wg!6(jj1+7)m!h3k6g0he3kwq_@4^0^fro'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'serverAPI'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'server.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'server.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql', # 数据库引擎
        'NAME': 'nodedb', # 数据库名
        'USER': 'root', # 账号
        'PASSWORD': 'c99y10w28', # 密码
        'HOST': '127.0.0.1', # HOST
        'POST': 3306, # 端口
    },
    'dataDB': {
        'ENGINE': 'django.db.backends.mysql', # 数据库引擎
        'NAME': 'datadb', # 数据库名
        'USER': 'root', # 账号
        'PASSWORD': 'c99y10w28', # 密码
        'HOST': '127.0.0.1', # HOST
        'POST': 3306, # 端口
    },
    'cloudDB': {
        'ENGINE': 'django.db.backends.mysql', # 数据库引擎
        'NAME': 'clouddb', # 数据库名
        'USER': 'root', # 账号
        'PASSWORD': 'tjubc12345', # 密码
        'HOST': 'bj-cdb-0tslvdym.sql.tencentcdb.com', # HOST
        'POST': 59568, # 端口
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SELF_INFO = {
    "address" : "2KBWT39ZCzL19Z7VA5adkzf8SrLqQZ7nXByiMmUVXobekNWHMH",
    "private_key" : "0e7abb12ff82e883fbaa410b0d22909b7efdd4e1c11c4f13a3f641edc67079d9",
    "loc_x" : 1,
    "loc_y" : 1,
    "AdjList" : [
        ("2vU96cFUEpLyUPnChizTaks52d8KcFra8WfE1XUji5txzRacDw","127.0.0.1:8001")
        # , ("2RVPR4ixP2c92XBt3JjBeHUfUpLfgS6SCJdPP5HC1qa3hYrQVJ","127.0.0.1:8003")
        # , ("2Bn2hnmfr9VWHGpeEH6JcZFqDLuxBCoLNAro5D1KV7VMaqrsha","127.0.0.1:8004")
    ],
    "node_status": 0,
    "data_status":0,
    "bc_port":1235,
    "server":"127.0.0.1:8000",
    "CacheRemained":3
}