# Generated by Django 4.0.3 on 2022-11-27 11:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortTermCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('loc_x', models.FloatField()),
                ('loc_y', models.FloatField()),
                ('type', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('content', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'short_term_cache',
                'unique_together': {('create_time', 'loc_x', 'loc_y', 'type')},
            },
        ),
    ]
