# Generated by Django 4.0.3 on 2022-12-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverAPI', '0002_adjinfo_selfinfo_longtermcache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjinfo',
            name='nodeIP',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='selfinfo',
            name='address',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='selfinfo',
            name='chain_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='selfinfo',
            name='private_key',
            field=models.CharField(max_length=255),
        ),
    ]
