# Generated by Django 4.0.3 on 2022-12-06 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverAPI', '0003_alter_adjinfo_nodeip_alter_selfinfo_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjinfo',
            name='selfAddr',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='adjinfo',
            name='nodeIP',
            field=models.CharField(default='', max_length=255),
        ),
    ]
