# Generated by Django 4.0.3 on 2022-12-07 20:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverAPI', '0005_adjinfo_destaddr'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorttermcache',
            name='acc_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='dataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_x', models.FloatField()),
                ('loc_y', models.FloatField()),
                ('type', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('content', models.CharField(max_length=256)),
                ('popularity', models.IntegerField()),
            ],
            options={
                'db_table': 'map_data',
                'unique_together': {('loc_x', 'loc_y', 'type')},
            },
        ),
    ]
