# Generated by Django 4.0.3 on 2022-12-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverAPI', '0006_shorttermcache_acc_count_datapoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='longtermcache',
            name='owner',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='shorttermcache',
            name='owner',
            field=models.CharField(default='', max_length=255),
        ),
    ]
