# Generated by Django 4.0.3 on 2022-12-10 19:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverAPI', '0008_selfinfo_round_time_alter_selfinfo_last_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=255)),
                ('round', models.PositiveIntegerField()),
                ('data_hash', models.CharField(max_length=255)),
                ('result', models.BooleanField()),
            ],
            options={
                'db_table': 'checkpoint',
            },
        ),
        migrations.AlterField(
            model_name='selfinfo',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 10, 19, 55, 42, 295680)),
        ),
        migrations.AlterField(
            model_name='selfinfo',
            name='round_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 10, 19, 55, 42, 295680)),
        ),
    ]
