# Generated by Django 4.0.3 on 2022-12-13 16:11

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverAPI', '0011_longtermcache_create_round_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField()),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('create_round', models.IntegerField(default=0)),
                ('upload_round', models.PositiveIntegerField()),
                ('loc_x', models.FloatField()),
                ('loc_y', models.FloatField()),
                ('type', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('data_hash', models.CharField(max_length=256)),
                ('content', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='longtermcache',
            name='data_hash',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='longtermcache',
            name='uploaded',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='selfinfo',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 13, 16, 11, 35, 446427)),
        ),
        migrations.AlterField(
            model_name='selfinfo',
            name='round_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 13, 16, 11, 35, 446427)),
        ),
    ]
