# Generated by Django 4.0.3 on 2022-12-13 19:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverAPI', '0014_alter_selfinfo_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfinfo',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 13, 19, 34, 31, 930918)),
        ),
        migrations.AlterField(
            model_name='selfinfo',
            name='round_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 13, 19, 34, 31, 930918)),
        ),
    ]
