# Generated by Django 4.0.3 on 2022-12-16 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverAPI', '0016_alter_selfinfo_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfinfo',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 16, 16, 55, 7, 99490)),
        ),
        migrations.AlterField(
            model_name='selfinfo',
            name='round_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 16, 16, 55, 7, 99490)),
        ),
        migrations.AlterUniqueTogether(
            name='longtermcache',
            unique_together={('owner', 'create_time', 'loc_x', 'loc_y', 'type')},
        ),
        migrations.AlterUniqueTogether(
            name='shorttermcache',
            unique_together={('owner', 'create_time', 'loc_x', 'loc_y', 'type')},
        ),
    ]
